# Enable all collectors. Same as specifying all --collector.<name>"
collect-all = false
# Enable autodiscover collections
discovering-mode = true
# Enable old mongodb-exporter compatible metrics
compatible-mode = true
# Treat each node in cluster as a separate target
split-cluster = false

[log]
# Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal]
level = error

[web]
# Address to listen on for web interface and telemetry
listen-address = :42003
# Metrics expose path
telemetry-path = /metrics
# Path to YAML file with server_user, server_password options for http basic auth (overrides HTTP_AUTH env var)
auth-file = /opt/ss/ssm-client/ssm.yml

[collector]
# Enable collecting metrics about the exporter itself (process_*, go_*)
exporter-metrics = true
# Enable collecting metrics from getDiagnosticData
diagnosticdata = true
# Enable collecting metrics from replSetGetStatus
replicasetstatus = true
# Enable collecting metrics from replSetGetConfig
replicasetconfig = false
# Enable collecting metrics from dbStats
dbstats = true
# Enable collecting free space metrics from dbStats
dbstatsfreestorage = false
# Enable collecting metrics from top admin command
topmetrics = true
# Enable collecting metrics currentop admin command
currentopmetrics = false
# Enable collecting metrics from $indexStats
indexstats = true
# Enable collecting metrics from $collStats
collstats = true
# Enable collecting metrics from profile
profile = false
# Enable Feature Compatibility Version collector
fcv = false
# Enable collecting metrics from sharded Mongo clusters about chunks
shards = false
# Enable collecting metrics from Percona Backup for MongoDB
pbm = false
# Disable collstats, dbstats, topmetrics and indexstats collector if there are more than <n> collections. 0=No limit
collstats-limit = 0
# Enable collecting index details and wired tiger metrics from $collStats
collstats-enable-details = false
# Set time for scrape slow queries.
profile-time-ts = 30
# Set minimum time for registration queries.
currentopmetrics-slow-time = 5m

[mongodb]
# MongoDB URI, format: [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]
uri = mongodb://localhost:27017
# monitor user, need clusterMonitor role in admin db and read role in local db
user =
# monitor user password
password =
# Use global connection pool instead of creating new pool for each http request.
global-conn-pool = true
# Whether or not a direct connect should be made. Direct connections are not valid if multiple hosts are specified or an SRV URI is used.
direct-connect = true
# Connection timeout in milliseconds
connect-timeout-ms = 1000
# List of comma separared databases.collections to get $collStats
collstats-colls =
# List of comma separared databases.collections to get $indexStats
indexstats-colls =
# Enable tls connection with mongo server
tls = 0
# Path to PEM file that contains the certificate (and optionally also the decrypted private key in PEM format).
# This should include the whole certificate chain.
# If provided: The connection will be opened via TLS to the MongoDB server.
tls-cert =
# Path to PEM file that contains the decrypted private key (if not contained in mongodb.tls-cert file)
tls-private-key =
# Path to PEM file that contains the CAs that are trusted for server connections.
# If provided: MongoDB servers connecting to should present a certificate signed by one of this CAs.
# If not provided: System default CAs are used.
tls-ca = 
# Disable hostname validation for server connection
disable-hostname-validation = 0

[groups]
# Currently ignored
enabled = 
